### ISSUE TITLE
Using heroku-buildpack-multi

### ISSUE THREAD

**Issue by joeyespo** [heroku/heroku-container-tools#105]
I'm using the `heroku-buildpack-multi` with the following `.buildpacks`

```
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-python.git
```

Using `heroku docker:init` is writing a Dockerfile for just Node.js. Should this case be considered?

And in the meantime, does anyone have a good Dockerfile for this combination?

**Comment by boboldehampsink** [comment]
It seems like docker:release also does NOT work with multiple buildpacks

**Comment by friism** [comment]
Hi, Dockerfiles and Docker images are not composable in the way that buildpacks are, and also note that the current Docker implementation does not use Buildpacks at all.

If you want, you should be able to build your own Dockerfile from the [Python](https://github.com/heroku/docker-python) and [Node](https://github.com/heroku/docker-nodejs) ones. If you copy over lines from those files to create your own one, be sure to remove the `ONBUILD` prefix, as those instructions will only be invoked from derived Dockerfiles.

Michael

**Comment by friism** [comment]
Also, would love to get your feedback on how you would ideally want this to work.

Michael

**Comment by Alaneor** [comment]
In the ideal scenario, the local Docker build process would mirror exactly what Heroku does when it compiles the application.

The Docker image can be based on the official Cedar image. Within that image, the initial buildpack can be detected via _app.json_ (there's a `buildpacks` array for that purpose already), which would pull that buildpack and let it do its work.

This would be a great boon to my local development workflow as almost all apps I deploy to Heroku have multiple buildpacks.

**Comment by joeyespo** [comment]
@jbyrum Does closing this mean it was fixed? Is there a related PR?

**Comment by jbyrum** [comment]
Thanks Joe -- I've emailed you privately to help debug the issue.
