### ISSUE TITLE
env in app.json is not used

### ISSUE THREAD

**Issue by hone** [heroku/heroku-container-tools#115]
I'm trying to work around the `SECRET_KEY_BASE` issue with any modern Rails app with heroku-docker and ruby. For context, rails can read `SECRET_KEY_BASE` as an env var to base it's secrets off of (think cookies etc). In the ruby buildpack, this is set in `bin/release`, but there's no good mechanism to do this with heroku-docker.

@friism suggested using [env in `app.json`](https://devcenter.heroku.com/articles/app-json-schema#env). I've added it to my `app.json`, but when I create a new heroku app and `heroku docker:release`, I don't see it available. I don't believe the plugin is parsing the `env` key at all for deployment or locally.

**Comment by friism** [comment]
This should arguably also go into docker-compose.yml that we generate.

Amazingly, docker-compose even supports .env files: https://docs.docker.com/compose/yml/#environment

**Comment by hone** [comment]
@friism the downside if putting it in docker-compose.yml, is that if someone edtis `app.json` you'll have to re-init, unless that's the expected workflow. I assume any `app.json`/`Procfile` changes will require a re-init.

**Comment by hunterloftis** [comment]
@hone how about `env_file` - that way you wouldn't have to re-init on changes (as you could just update the env in .env)

**Comment by hone** [comment]
that probably works fine. we'd need a way to create it as a language docker
template curator. ideally, I'd like this to be seamless with users if
possible. is there a reason we shouldn't just support the existing
`app.json` stuff?

**Comment by hunterloftis** [comment]
we can pull env out of app.json; I thought you said that's not what you wanted because then you'd have to `heroku docker:init` on changes.

**Comment by friism** [comment]
I think there's gonna be a flow where folks run `init` irregularly, eg. to update language version, get changes from Procfile and so forth - @hunterloftis can we re-introduce the notion of hashing the contents of the files that go into Dockerfile and docker-compose.yml and warning if they've gotten stale?

**Comment by hunterloftis** [comment]
@friism certainly. Can also make a branch that does diffing instead of overwriting for easier updates.

**Comment by hone** [comment]
yeah, that makes sense. I was just pointing out the downside not sure of
what the expected user flow should be.

**Comment by friism** [comment]
I just re-read this. We need to come up with a consistent way for app env to be specified and used with Docker. It feels suspect if some env is in `app.json`, other in assorted `.env` and some is in `docker-compose.yml`, added by hand.

I prefer `app.json`, also because we can use the generators (eg. secret) and because we can use contents of `app.json` to make sure app deployed to during `docker:release` has the right env.

@hone what do you think having also used .env files to do tests?

Also /cc @markpundsack. Do you remember if thought was ever given to have `test` or `debug` sections for app.json?

**Comment by hunterloftis** [comment]
I'd be interested in hearing how @hone's experiments with running tests via modded heroku-docker output have gone.

Also +1 for `app.json` env if that's feasible. One source-of-truth vs littering `.` with yet more config files.

**Comment by hone** [comment]
I haven't modded heroku-docker at all. I've just been using it as is, you
can see where I've gone in [my fork of prism](
https://github.com/hone/prism/tree/dockerize). `app.json` doesn't support
per env (like test/dev/etc), env vars which makes it hard without changing
the schema there. I think one source of truth is great, but I've actually
just been leveraging docker-compose.yml's `env_file` so far and it's been
working ok. You can have a template and then override anything in the `env`
key in `docker-compose.yml`

`app.json` seems great, but like above it needs the ability to persist env
vars I believe if they're missing as config vars IMO. Also, I don't think
you can get away with just app.json env vars, b/c `docker:init`'s generated
env vars should be kept separate IMO. It's kind of like how addons
resources even though they are env vars, I believe should be separate from
user env vars.

**Comment by markpundsack** [comment]
Perhaps we should have a CLI way to instantiate .env from app.json. App.json has generators so using it directly doesn't make complete sense. 

Mark

**Comment by johnbeynon** [comment]
Did anything come of this - what's the best way with getting .env into a container?

**Comment by saulshanabrook** [comment]
I used [`jq`](https://stedolan.github.io/jq/) to extract all my set environmental variables from my `app.json` file so I could push them with `heroku config:push`:

```bash
jq '.env | with_entries(select(.value | type == "string")) | to_entries | map("\(.key)=\(.value)") | join("\n")' -r app.json  > .env
```
