### ISSUE TITLE
Invalid interpolation format for "command" option

### ISSUE THREAD

**Issue by jkutner** [heroku/heroku-container-tools#136]
```
$ git clone https://github.com/heroku/jruby-getting-started
$ cd jruby-getting-started
$ heroku docker:init --image heroku/jruby
$ docker-compose run shell
ERROR: Invalid interpolation format for "command" option in service "web": "bash -c 'puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}'"
```

This used to work.

**Comment by friism** [comment]
@hunterloftis looks like compose added new variable subsitution in 1.5:

 * https://github.com/docker/compose/blob/master/docs/compose-file.md#variable-substitution
 * https://github.com/docker/compose/issues/2269

**Comment by bwidmeier** [comment]
In summary, compose configs now supports environment variables and a dollar sign is interpreted as the beginning of a symbol referring to a environment variable local to the machine running docker-compose. If you want the dollar sign not to be interpreted that way, you need to escape it without a second dollar sign.

Examples:
${foo} will be replaced with the value of the foo environment variable as defined on the machine running docker compose
$${foo}, on the other hand, will be passed to the docker machine being targeted as ${foo}
