### ISSUE TITLE
Can't destroy containers/images on Circle CI

### ISSUE THREAD

**Issue by JakeChampion** [heroku/heroku-container-tools#138]
It seems Circle CI is not capable of destroying containers/images, it fails to remove btfs volumes and sub-volumes. When using the Docker CLI directly I can create and push images to a registry, when using the Heroku CLI I can't do anything because I believe the release process is running the container with `rm` flag enabled -- https://github.com/heroku/heroku-docker/blob/264244cca820b9d766cd820035f81ce10ef44a54/commands/release.js#L128

Would it be possible to have this flag configurable from the Heroku CLI?

**Comment by JakeChampion** [comment]
Here is a build on Circle that shows the issue -- https://circleci.com/gh/ftlabs/big-ft/60

**Comment by JakeChampion** [comment]
https://github.com/heroku/heroku-docker/pull/134 looks like it would resolve the issue.

**Comment by mohanzhang** [comment]
Would very much like this as well. Please consider merging #134

**Comment by dfuentes77** [comment]
Any reason why this was closed?  Is a better solution on the way?  I still don't see https://github.com/heroku/heroku-container-tools/pull/134 merged

**Comment by jbyrum** [comment]
Hello Damian -- Can you please email me at jbyrum@heroku.com so that we can discuss a workaround.

**Comment by JakeChampion** [comment]
Please could you keep the conversation in this thread, I'd like to know the solution also.
