### ISSUE TITLE
ERROR: Service 'web' failed to build: The command '/bin/sh -c composer install --no-scripts' returned a non-zero code: 1

### ISSUE THREAD

**Issue by themccallister** [heroku/heroku-container-tools#159]
I'm running a Laravel 5.1 app and trying to use the Heroku docker build images. However, this error is displaying when composer attempts to generate the classmaps.

> [RuntimeException]
> Could not scan for classes inside "database" which does not appear to be a file nor a folder

I can run the exact same command (`composer install --no-scripts`) in terminal and I do not see this issue until I run `docker-compose up -d`.

I initially thought this may be an issue with a plugin I have on my local system. However, it appears that the build is running the script inside of the container from this message:

> Step 1 : RUN composer install --no-scripts
> ---> Running in 8ae033a31b83

Any thoughts on how to resolve this?

**Comment by themccallister** [comment]
Looking through the repositories on Heroku... Should this issue be opened here or would it be best to open the issue on https://github.com/heroku/docker-php?

**Comment by themccallister** [comment]
Looks like this pull request will solve this issue, which has been open since November 2015:

https://github.com/heroku/docker-php/pull/14

**Comment by themccallister** [comment]
@jbyrum is this issue going to be addressed on the other repository? Right now using docker-php is unusable for Laravel development.

**Comment by jbyrum** [comment]
Thanks Jason -- I've sent you an email privately to diagnose the issue.
