### ISSUE TITLE
Deprecated repo is referenced in canonical docs

### ISSUE THREAD

**Issue by rossettistone** [heroku/heroku-container-tools#171]
The latest docs I can find for the Heroku Container Registry and Runtime (https://devcenter.heroku.com/articles/container-registry-and-runtime#getting-started) reference this plugin, and this repo references those docs as being the most up to date. Puzzlingly, though, this repo is marked at the top of the README as being deprecated.

Is there a better replacement for this repo or those docs to which I should refer? 

Thanks!

**Comment by dmathieu** [comment]
Hi Mark,

This documentation references [heroku-container-registry](https://github.com/heroku/heroku-container-registry).
Where do you see a reference to this repo in there?

cc @jbyrum

**Comment by rossettistone** [comment]
You're absolutely correct. My mistake! Thanks for taking the time to look at this so quickly.
