### ISSUE TITLE
`ONBUILD RUN npm install` is occasionally confused by existing `node_modules`

### ISSUE THREAD

**Issue by friism** [heroku/heroku-container-tools#56]
It's intermittent, but I sometimes see problems with `npm` install on `start` and `release`. Because we're running as `app` use we can't do `rm -rf node_modules`. There are various hacks in this issues: https://github.com/docker/docker/issues/2224#issuecomment-41395152

**Comment by JakeChampion** [comment]
Do we know when this will be resolved? I'm currently having to work around this issue in the CI environment. We want to install development deps for running the tests and then in the Dockerfile prune the node modules for only production used modules, this currently fails as the app user can not edit the node_modules folder that is imported into the Dockerfile's context.
