### ISSUE TITLE
detect() for scala requires wild card expansion?

### ISSUE THREAD

**Issue by tkawachi** [heroku/heroku-container-tools#67]
I've tried `docker:init` with a project which has `build.sbt` in the root directory. Unexpectedly it's detected as minimal.
I added some debug print and found that the following condition doesn't match.

    if (exists.sync(path.resolve(dir, '*.sbt'))) return true;

I suppose expanding the wildcard is needed.

**Comment by hunterloftis** [comment]
pinging @jkutner

I think what the scala buildpack wants (instead of `exists.sync` and `path.resolve`) is `glob`:

- https://github.com/isaacs/node-glob

**Comment by jkutner** [comment]
Yup, I'll update this. Thanks

**Comment by jkutner** [comment]
Fixed in 2a5911f88ee9dbb7d6d4995b3934837045568cbb as part of #61
