### ISSUE TITLE
Haskell support

### ISSUE THREAD

**Issue by srid** [heroku/heroku-container-tools#74]
If anybody wants to properly add support for Haskell and Elm, feel free to take a look at my Dockerfile (it is tied to my app, thus not for generic use, but you may be able to adapt it).

https://github.com/srid/elm-laundrycoins/blob/master/Dockerfile

**Comment by matsrietdijk** [comment]
If you are using stack, pbrisbin's https://github.com/pbrisbin/docker-heroku-haskell-stack works quite well.
