### ISSUE TITLE
Dynamic mounted directory

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-container-tools#76]
Both Java and Go folks have shown that this would be useful for their platforms. Thinking a dynamic key in the platform object like `mountDir()`:

```js
mountDir: function(cwd) {
  return '/app/src'; // for Node
}
```

To be used instead of the magic dir here: https://github.com/heroku/heroku-docker/blob/7c6f7efb5d708b64ac6d1508983f8b93f6ed166d/lib/docker.js#L52

/cc @freeformz @jkutner

**Comment by freeformz** [comment]
That works for me as I'd be able to lookup what I need in the `Godeps/Godeps.json` file and DTRT.
