### ISSUE TITLE
How can we avoid duplication?

### ISSUE THREAD

**Issue by hunterloftis** [heroku/heroku-container-tools#81]
The Dockerfiles must create containers that are executable in three different environments:

- `:exec`
- `:start`
- on Heroku

Currently, the config is separate for local and remove execution. Exec and start rely on Docker config (https://github.com/heroku/heroku-docker/blob/master/platforms/node/Dockerfile.t#L14), while Heroku relies on .profile.d.

Should we somehow have `exec` and `start` run .profile.d as well?

**Comment by hunterloftis** [comment]
Possible solution with forego: https://github.com/jesperfj/heroku-dockerfiles/blob/master/docker-base/Dockerfile#L8

**Comment by friism** [comment]
Current solution: https://github.com/hunterloftis/node-image/blob/master/init

**Comment by hunterloftis** [comment]
https://github.com/heroku/heroku-docker/tree/compose uses docker-compose and doesn't have separate exec/start steps. It only has behavior analogous to `start`, no volume mounting. Uses an `init` script within the docker hub image to run `.profile.d` scripts. If this approach makes sense, we can factor `init` into a base image from which the platform implementations can inherit.

**Comment by hunterloftis** [comment]
`init` helps but doesn't totally solve the problem: https://github.com/hunterloftis/node-image/commit/1069079e6cef3de49671cdf9cffb7426538c2154

**Comment by friism** [comment]
nnggh!
