### ISSUE TITLE
Unable to use ENV in Procfile with heroku docker:start

### ISSUE THREAD

**Issue by joeyespo** [heroku/heroku-container-tools#94]
When I have the following:

```procfile
web: gunicorn --error-logfile=- wsgi -b 0.0.0.0:$PORT
```

I get this error:

```
Error: '$PORT' is not a valid port number.
```

I see that `PORT` is set in the Dockerfile:

```dockerfile
ENV PORT 3000
```

So it looks like environment variables cannot be used in Procfiles when using `heroku docker:start`. Since they resolve with Foreman and when using `git push` deploys, this seems like a bug.

**Comment by hunterloftis** [comment]
We're sorting a way around this... probably some sort of `bash -c` hack, since Docker doesn't evaluate env vars in the `CMD`.

**Comment by joeyespo** [comment]
@jbyrum You closed this issue without any further explanation. Was it fixed?
