### ISSUE TITLE
Runtime Python3 error: /app/.heroku/python/bin/python: error while loading shared libraries: libpython3.3m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by corentone** [heroku/heroku-container-tools#99]
Hello, 

I have a python app, if I use a runtime.txt which is a python3 version, I get the following:

```
/app/.heroku/python/bin/python: error while loading shared libraries: libpython3.3m.so.1.0: cannot open shared object file: No such file or directory
```

---

1. `heroku docker:init` works fine.
2. `heroku docker:start` fails
End of output:
```
Successfully built 5766f51ef95f

starting container...
web process will be available at http://192.168.59.103:3000/
/app/.heroku/python/bin/python: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory
```

I was able to start the container and get into it to check, and trying to run the python gives the error:
```
app@e2aca7275c1a:~/.heroku/python/bin$ ./python
./python: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory
```
Setting up the LD_LIBRARY_PATH seems to solve the issue:
```
app@e2aca7275c1a:~/.heroku/python/bin$ echo $LD_LIBRARY_PATH

app@e2aca7275c1a:~/.heroku/python/bin$ export LD_LIBRARY_PATH=/app/.heroku/python/lib/
app@e2aca7275c1a:~/.heroku/python/bin$ ./python
Python 3.4.3 (default, Mar 17 2015, 18:15:40) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Python 2.7.x works fine with the runtime.txt or without.
Any suggestion? Thanks!

**Comment by droustchev** [comment]
Just ran into the same issue. @corentone, were you able to solve it?

**Comment by corentone** [comment]
@droustchev unfortunately I wasn't able to solve it and dropped using heroku-docker.

**Comment by droustchev** [comment]
Hey Corentin, thanks for taking the time to reply! Appreciated!

**Comment by jambonrose** [comment]
Warning: I started using Docker and `heroku-docker` yesterday; I have no idea what I'm talking about.

Without more information it's hard to tell, but I suspect the problem stems from the fact that the docker Python image appears to [ignore runtime versions and uses Python 2.7 (see line 7)](https://github.com/heroku/docker-python/blob/f39a9a80ff03a7f5bebb74a3a28dbcc064bea089/Dockerfile).

You may be interested in [sstewart78's fork](https://github.com/sstewart78/docker-python) which changes the version to Python 3.5.

**Comment by aleccool213** [comment]
Why wouldn't Heroku have a 3.4 version of this image up? so confused. But thanks for fork @sstewart78. 

Receiving a `ERROR: Service 'web' failed to build: lstat init: no such file or directory` at STEP 7 of the Dockerfile still. When I take that line out I still get the error above :/
